---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s %(levelname)-8s - [%(name)s.%(funcName)s:%(lineno)d] %(message)s"
    datefmt: "%d-%b-%Y %H:%M:%S:%z"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: qa-webapi-info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: qa-webapi-errors.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
  urllib3.connectionpool:
    level: INFO
    propogate: yes

  google:
    level: INFO
    propogate: yes

root:
  level: DEBUG
  handlers: [console, info_file_handler, error_file_handler]
